@baseUrl = https://localhost:7062

@productId = 2779ee47-10b0-4bd7-8342-404006aa1392


###
GET {{baseUrl}}/api/products?page=1&pageSize=100


###
GET {{baseUrl}}/api/products/{{productId}}

###
GET {{baseUrl}}/api/products/{{productId}}?includeReviews=true

###
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "keyboard",
  "price": 34.99
}


# ###
# POST {{baseUrl}}/api/products/{{productId}}/reviews
# Content-Type: application/json

# {
#   "reviewer": "Kevin Kelo",
#   "stars": 3
# }

###
POST {{baseUrl}}/api/products/{{productId}}/reviews
Content-Type: application/json

{
  "reviewer": "{{$guid}}",
  "stars": 5
}
### this link we get it from the previous header location that we get it from the post request
GET  https://localhost:7062/api/products/ef60f888-d785-4d2c-8bf2-464e6cb18c68

### update only once
PUT {{baseUrl}}/api/products/{{productId}}
Content-Type: application/json

{
  "name": "chocolate bar",
  "price": 3.50
}



###
DELETE {{baseUrl}}/api/products/{{productId}}

