@baseUrl = https://localhost:9191

###
GET {{baseUrl}}/api/bids

###
GET {{baseUrl}}/api/bids/2e2e73cd-3902-4564-954b-5c04814e861b

###
POST {{baseUrl}}/api/bids
content-type: application/json

{
  "amount": 150.00,
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "telephone": "+1234567890",
  "location": "Amman",
  "address": "123 Rainbow Street"
}
