@baseUrl = https://localhost:7007


###
GET {{baseUrl}}/product/20

###
{{baseUrl}}/date/2025-12-3

###
{{baseUrl}}/
###
{{baseUrl}}/products
###
{{baseUrl}}/users

###
{{baseUrl}}/users/5

###
{{baseUrl}}/abxcd

###
{{baseUrl}}/aabxcd

###
{{baseUrl}}/single/my/path/test/wire

###
{{baseUrl}}/single/my%2Fpath

###
{{baseUrl}}/double/my%2Fpath


